spring:
  datasource:
    url: jdbc:mysql://localhost:3306/portafoglio
    username: portafoglio
    password: portapass
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
  logging:
    level:
      org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
      org.springframework.boot.autoconfigure.jdbc.DataSourceInitializer: DEBUG
      org.springframework.boot.autoconfigure.jdbc: DEBUG
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

  jpa:
    hibernate:
      ddl-auto: none

server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: portafoglio